### ISSUE TITLE
bug with assumptions in cnf_view

### ISSUE THREAD

**Issue by lee30sonia** [lsils/mockturtle#303] opened 2020-03-30 12:17 UTC
A test case that fails:

```C++
TEST_CASE( "bug in assumptions", "[cnf_view]" )
{
  cnf_view<xag_network> xag;
  const auto a = xag.create_pi();
  const auto b = xag.create_pi();

  const auto f = xag.create_xor( a, b );
  const auto g = xag.create_xor( f, f );

  /* if delete the following 4 lines, this test case will pass */
  bill::result::clause_type assump1( 1, xag.lit(f) );
  const auto result1 = xag.solve( assump1 );
  CHECK( result1 );   /* has result */
  CHECK( *result1 ); /* result is SAT */

  bill::result::clause_type assump2( 1, xag.lit(g) );
  const auto result2 = xag.solve( assump2 );
  CHECK( result2 );   /* has result */
  CHECK( !*result2 ); /* result is UNSAT */ /* this check fails */
}
```

**Comment by lee30sonia** [comment] 2020-03-30 12:30
Also if I add `xag.add_clause( assump1 );` after the first solve, it will pass.

**Comment by msoeken** [comment] 2020-03-31 09:18
Thanks for the bug report. This seems to fail with the default solver in `cnf_view`, which is `glucose_41`, but it does not happen when changing the solver to, e.g., `bsat2`. It may be that the problem is rooted in *bill*. I suggest to make a test case in bill that directly accesses the solver interface and check whether the problem still occurs.

**Comment by msoeken** [comment] 2020-03-31 09:39
Problem seems to be in *bill*, not `cnf_view`. Re-opened with new test case in lsils/bill#22. Closing this one.

**Closed by msoeken** 2020-03-31 09:39 UTC
